/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.0.0                                               */
/*  Date (dd.mm.yyyy):  8.12.2020   Time (hh:mm): 21:27                        */
/*******************************************************************************/


#include "gx_api.h"
#include "flipdot_guix_resources.h"

/* Color Table                                                                 */

GX_CONST GX_COLOR display_theme_1_color_table[] =
{
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000001,
    0x00000001,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000000,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000001,
    0x00000001,
    0x00000000,
    0x00000001,
    0x00000000
};


/* Font THEME_1_flipdotfont3by5 Data Definition                                */

static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_21[5] =
{
    0x80, 0x80, 0x80, 0x00, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_22[2] =
{
    0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_23[5] =
{
    0xa0, 0xe0, 0xa0, 0xe0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_24[5] =
{
    0x60, 0xc0, 0x40, 0x60, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_25[5] =
{
    0x80, 0x20, 0x40, 0x80, 0x20
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_26[5] =
{
    0x60, 0x80, 0x60, 0xa0, 0x60
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_27[2] =
{
    0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_28[5] =
{
    0x40, 0x80, 0x80, 0x80, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_29[5] =
{
    0x80, 0x40, 0x40, 0x40, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_2a[5] =
{
    0xa0, 0x40, 0xe0, 0x40, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_2b[3] =
{
    0x40, 0xe0, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_2c[2] =
{
    0x40, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_2d[1] =
{
    0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_2e[1] =
{
    0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_2f[5] =
{
    0x20, 0x20, 0x40, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_30[5] =
{
    0xe0, 0xa0, 0xa0, 0xa0, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_31[5] =
{
    0x40, 0xc0, 0x40, 0x40, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_32[5] =
{
    0xc0, 0x20, 0x40, 0x80, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_33[5] =
{
    0xc0, 0x20, 0x40, 0x20, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_34[5] =
{
    0xa0, 0xa0, 0xe0, 0x20, 0x20
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_35[5] =
{
    0xe0, 0x80, 0xc0, 0x20, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_36[5] =
{
    0x60, 0x80, 0xc0, 0xa0, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_37[5] =
{
    0xe0, 0x20, 0x40, 0x40, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_38[5] =
{
    0x40, 0xa0, 0x40, 0xa0, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_39[5] =
{
    0x40, 0xa0, 0x60, 0x20, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_3a[3] =
{
    0x80, 0x00, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_3b[4] =
{
    0x40, 0x00, 0x40, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_3c[5] =
{
    0x20, 0x40, 0x80, 0x40, 0x20
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_3d[3] =
{
    0xe0, 0x00, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_3e[5] =
{
    0x80, 0x40, 0x20, 0x40, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_3f[5] =
{
    0xc0, 0x20, 0x40, 0x00, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_40[5] =
{
    0x40, 0xa0, 0xe0, 0x80, 0x60
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_41[5] =
{
    0x40, 0xa0, 0xe0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_42[5] =
{
    0xc0, 0xa0, 0xc0, 0xa0, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_43[5] =
{
    0x40, 0xa0, 0x80, 0xa0, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_44[5] =
{
    0xc0, 0xa0, 0xa0, 0xa0, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_45[5] =
{
    0xe0, 0x80, 0xe0, 0x80, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_46[5] =
{
    0xe0, 0x80, 0xe0, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_47[5] =
{
    0x60, 0x80, 0x80, 0xa0, 0x60
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_48[5] =
{
    0xa0, 0xa0, 0xe0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_49[5] =
{
    0x80, 0x80, 0x80, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_4a[5] =
{
    0x20, 0x20, 0x20, 0xa0, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_4b[5] =
{
    0xa0, 0xa0, 0xc0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_4c[5] =
{
    0x80, 0x80, 0x80, 0x80, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_4d[5] =
{
    0xa0, 0xe0, 0xa0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_4e[5] =
{
    0xc0, 0xa0, 0xa0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_4f[5] =
{
    0x40, 0xa0, 0xa0, 0xa0, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_50[5] =
{
    0xc0, 0xa0, 0xc0, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_51[5] =
{
    0x40, 0xa0, 0xa0, 0xe0, 0x60
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_52[5] =
{
    0xc0, 0xa0, 0xc0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_53[5] =
{
    0x60, 0x80, 0x40, 0x20, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_54[5] =
{
    0xe0, 0x40, 0x40, 0x40, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_55[5] =
{
    0xa0, 0xa0, 0xa0, 0xa0, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_56[5] =
{
    0xa0, 0xa0, 0xa0, 0xe0, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_57[5] =
{
    0xa0, 0xa0, 0xa0, 0xe0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_58[5] =
{
    0xa0, 0xa0, 0x40, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_59[5] =
{
    0xa0, 0xa0, 0xe0, 0x40, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_5a[5] =
{
    0xe0, 0x20, 0x40, 0x80, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_5b[5] =
{
    0xc0, 0x80, 0x80, 0x80, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_5c[5] =
{
    0x80, 0x80, 0x40, 0x20, 0x20
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_5d[5] =
{
    0xc0, 0x40, 0x40, 0x40, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_5e[2] =
{
    0x40, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_5f[1] =
{
    0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_60[2] =
{
    0x80, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_61[5] =
{
    0x40, 0xa0, 0xe0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_62[5] =
{
    0xc0, 0xa0, 0xc0, 0xa0, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_63[5] =
{
    0x40, 0xa0, 0x80, 0xa0, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_64[5] =
{
    0xc0, 0xa0, 0xa0, 0xa0, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_65[5] =
{
    0xe0, 0x80, 0xe0, 0x80, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_66[5] =
{
    0xe0, 0x80, 0xe0, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_67[5] =
{
    0x60, 0x80, 0x80, 0xa0, 0x60
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_68[5] =
{
    0xa0, 0xa0, 0xe0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_69[5] =
{
    0x80, 0x80, 0x80, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_6a[5] =
{
    0x20, 0x20, 0x20, 0xa0, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_6b[5] =
{
    0xa0, 0xa0, 0xc0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_6c[5] =
{
    0x80, 0x80, 0x80, 0x80, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_6d[5] =
{
    0xa0, 0xe0, 0xa0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_6e[5] =
{
    0xc0, 0xa0, 0xa0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_6f[5] =
{
    0x40, 0xa0, 0xa0, 0xa0, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_70[5] =
{
    0xc0, 0xa0, 0xc0, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_71[5] =
{
    0x40, 0xa0, 0xa0, 0xe0, 0x60
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_72[5] =
{
    0xc0, 0xa0, 0xc0, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_73[5] =
{
    0x60, 0x80, 0x40, 0x20, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_74[5] =
{
    0xe0, 0x40, 0x40, 0x40, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_75[5] =
{
    0xa0, 0xa0, 0xa0, 0xa0, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_76[5] =
{
    0xa0, 0xa0, 0xa0, 0xe0, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_77[5] =
{
    0xa0, 0xa0, 0xa0, 0xe0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_78[5] =
{
    0xa0, 0xa0, 0x40, 0xa0, 0xa0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_79[5] =
{
    0xa0, 0xa0, 0xe0, 0x40, 0x40
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_7a[5] =
{
    0xe0, 0x20, 0x40, 0x80, 0xe0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_7b[5] =
{
    0x60, 0x40, 0xc0, 0x40, 0x60
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_7c[5] =
{
    0x80, 0x80, 0x00, 0x80, 0x80
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_7d[5] =
{
    0xc0, 0x40, 0x60, 0x40, 0xc0
};
static GX_CONST GX_UBYTE FONT_THEME_1_flipdotfont3by5_char_7e[2] =
{
    0x60, 0xc0
};
static GX_CONST GX_GLYPH THEME_1_flipdotfont3by5_FONT_PAGE_1_GLYPHS[95] =
{
    {GX_NULL, 0, 0, 3, 0, 0, 0},
    {FONT_THEME_1_flipdotfont3by5_char_21, 5, 0, 2, 0, 1, 5},
    {FONT_THEME_1_flipdotfont3by5_char_22, 5, -3, 4, 0, 3, 2},
    {FONT_THEME_1_flipdotfont3by5_char_23, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_24, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_25, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_26, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_27, 5, -3, 2, 0, 1, 2},
    {FONT_THEME_1_flipdotfont3by5_char_28, 5, 0, 3, 0, 2, 5},
    {FONT_THEME_1_flipdotfont3by5_char_29, 5, 0, 3, 0, 2, 5},
    {FONT_THEME_1_flipdotfont3by5_char_2a, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_2b, 4, -1, 4, 0, 3, 3},
    {FONT_THEME_1_flipdotfont3by5_char_2c, 2, 0, 3, 0, 2, 2},
    {FONT_THEME_1_flipdotfont3by5_char_2d, 3, -2, 4, 0, 3, 1},
    {FONT_THEME_1_flipdotfont3by5_char_2e, 1, 0, 2, 0, 1, 1},
    {FONT_THEME_1_flipdotfont3by5_char_2f, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_30, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_31, 5, 0, 4, 0, 2, 5},
    {FONT_THEME_1_flipdotfont3by5_char_32, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_33, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_34, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_35, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_36, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_37, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_38, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_39, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_3a, 4, -1, 2, 0, 1, 3},
    {FONT_THEME_1_flipdotfont3by5_char_3b, 4, 0, 3, 0, 2, 4},
    {FONT_THEME_1_flipdotfont3by5_char_3c, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_3d, 4, -1, 4, 0, 3, 3},
    {FONT_THEME_1_flipdotfont3by5_char_3e, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_3f, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_40, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_41, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_42, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_43, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_44, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_45, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_46, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_47, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_48, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_49, 5, 0, 2, 0, 1, 5},
    {FONT_THEME_1_flipdotfont3by5_char_4a, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_4b, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_4c, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_4d, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_4e, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_4f, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_50, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_51, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_52, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_53, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_54, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_55, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_56, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_57, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_58, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_59, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_5a, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_5b, 5, 0, 3, 0, 2, 5},
    {FONT_THEME_1_flipdotfont3by5_char_5c, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_5d, 5, 0, 3, 0, 2, 5},
    {FONT_THEME_1_flipdotfont3by5_char_5e, 5, -3, 4, 0, 3, 2},
    {FONT_THEME_1_flipdotfont3by5_char_5f, 1, 0, 4, 0, 3, 1},
    {FONT_THEME_1_flipdotfont3by5_char_60, 5, -3, 3, 0, 2, 2},
    {FONT_THEME_1_flipdotfont3by5_char_61, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_62, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_63, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_64, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_65, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_66, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_67, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_68, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_69, 5, 0, 2, 0, 1, 5},
    {FONT_THEME_1_flipdotfont3by5_char_6a, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_6b, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_6c, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_6d, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_6e, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_6f, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_70, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_71, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_72, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_73, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_74, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_75, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_76, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_77, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_78, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_79, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_7a, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_7b, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_7c, 5, 0, 2, 0, 1, 5},
    {FONT_THEME_1_flipdotfont3by5_char_7d, 5, 0, 4, 0, 3, 5},
    {FONT_THEME_1_flipdotfont3by5_char_7e, 4, -2, 4, 0, 3, 2}
};

static GX_CONST GX_FONT THEME_1_flipdotfont3by5 = 
{
    GX_FONT_FORMAT_1BPP,                     /* format                         */
    0,                                       /* line pre-space                 */
    0,                                       /* line post-space                */ 
    5,                                       /* font data height               */
    5,                                       /* font baseline offset           */
    0x20,                                    /* first glyph within data page   */
    0x7e,                                    /* last glyph within data page    */
    {THEME_1_flipdotfont3by5_FONT_PAGE_1_GLYPHS},    /* pointer to glyph data  */
    GX_NULL                                  /* next font page                 */
};


/* Font Table                                                                  */


extern GX_FONT _gx_system_font_mono;
GX_CONST GX_FONT *display_theme_1_font_table[] =
{
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &_gx_system_font_mono,
    &THEME_1_flipdotfont3by5
};

/* Pixelmap data definitions                                                   */


/* THEME_1_RADIO_ON pixelmap data                                              */

static GX_CONST GX_UBYTE DISPLAY_THEME_1_RADIO_ON_pixelmap_data[64] =
{
    0x00, 0xf5, 0x5c, 0x00, 0x03, 0x7f, 0xfd, 0xc0, 0x0f, 0xfd, 0x7f, 0x70, 0x3f, 
    0xd5, 0x57, 0xdc, 0x1f, 0x55, 0x55, 0xf4, 0xfd, 0x55, 0x55, 0x7f, 0x7d, 0x55, 
    0x55, 0x7f, 0x75, 0x55, 0x55, 0x5d, 0x75, 0x55, 0x55, 0x5d, 0x7d, 0x55, 0x55, 
    0x5f, 0xfd, 0x55, 0x55, 0x7f, 0x1f, 0x55, 0x55, 0xf4, 0x3f, 0xd5, 0x57, 0xdc, 
    0x0f, 0xfd, 0x7f, 0x70, 0x03, 0x7f, 0xfd, 0xc0, 0x00, 0x35, 0x5c, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_THEME_1_RADIO_ON_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    GX_PIXELMAP_TRANSPARENT,                 /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_THEME_1_RADIO_ON_pixelmap_data,
    sizeof(DISPLAY_THEME_1_RADIO_ON_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_RADIO_OFF pixelmap data                                             */

static GX_CONST GX_UBYTE DISPLAY_THEME_1_RADIO_OFF_pixelmap_data[64] =
{
    0x00, 0xd5, 0x54, 0x00, 0x01, 0x55, 0x55, 0x00, 0x05, 0x5f, 0xf5, 0x50, 0x15, 
    0xff, 0xff, 0x50, 0x17, 0xff, 0xff, 0xd4, 0x57, 0xff, 0xff, 0xd5, 0x5f, 0xff, 
    0xff, 0xf5, 0x5f, 0xff, 0xff, 0xf5, 0x5f, 0xff, 0xff, 0xf5, 0x5f, 0xff, 0xff, 
    0xf5, 0x57, 0xff, 0xff, 0xd5, 0x17, 0xff, 0xff, 0xd4, 0x15, 0xff, 0xff, 0x50, 
    0x05, 0x5f, 0xf5, 0x50, 0x01, 0x55, 0x55, 0xc0, 0x00, 0x15, 0x54, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_THEME_1_RADIO_OFF_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    GX_PIXELMAP_TRANSPARENT,                 /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_THEME_1_RADIO_OFF_pixelmap_data,
    sizeof(DISPLAY_THEME_1_RADIO_OFF_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_CHECKBOX_ON pixelmap data                                           */

static GX_CONST GX_UBYTE DISPLAY_THEME_1_CHECKBOX_ON_pixelmap_data[32] =
{
    0x00, 0x00, 0x7f, 0xfc, 0x7f, 0xfe, 0x7f, 0xfe, 0x7f, 0xee, 0x7f, 0xce, 0x77, 
    0x8e, 0x73, 0x1e, 0x72, 0x1e, 0x70, 0x3e, 0x78, 0x7c, 0x7d, 0xfc, 0x7f, 0xfc, 
    0x7f, 0xfe, 0x3f, 0xc4, 0x00, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_THEME_1_CHECKBOX_ON_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    0,                                       /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_THEME_1_CHECKBOX_ON_pixelmap_data,
    sizeof(DISPLAY_THEME_1_CHECKBOX_ON_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* THEME_1_CHECKBOX_OFF pixelmap data                                          */

static GX_CONST GX_UBYTE DISPLAY_THEME_1_CHECKBOX_OFF_pixelmap_data[32] =
{
    0x00, 0x00, 0x7f, 0xfc, 0x7f, 0xfe, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 
    0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 0x7f, 0xfc, 
    0x7f, 0xfc, 0x20, 0x00, 0x00, 0x00
};
GX_CONST GX_PIXELMAP DISPLAY_THEME_1_CHECKBOX_OFF_pixelmap =
{
    0x00000001,                              /* major version                  */
    0x00000000,                              /* minor version                  */
    0,                                       /* flags                          */
    GX_COLOR_FORMAT_MONOCHROME,              /* Format                         */
    (GX_UBYTE *) DISPLAY_THEME_1_CHECKBOX_OFF_pixelmap_data,
    sizeof(DISPLAY_THEME_1_CHECKBOX_OFF_pixelmap_data),    /* the size of pixelmap_data*/
    NULL,
    0,                                       /* auxiliary data size            */
    0x00,                                    /* used for transparent iamges    */
    16,                                      /* width in pixel                 */
    16                                       /* height in pixel                */
};

/* Pixelmap Table                                                              */


GX_CONST GX_PIXELMAP *display_theme_1_pixelmap_table[] =
{
    GX_NULL,
    &DISPLAY_THEME_1_RADIO_ON_pixelmap,
    &DISPLAY_THEME_1_RADIO_OFF_pixelmap,
    &DISPLAY_THEME_1_CHECKBOX_ON_pixelmap,
    &DISPLAY_THEME_1_CHECKBOX_OFF_pixelmap
};

/* String values                                                               */

GX_CONST GX_UBYTE display_STRING_1_English[] = "...";

/* String Table for display language English                                   */

GX_CONST GX_STRING display_English_string_table[2] =
{
    {GX_NULL, 0},
    {(GX_CONST GX_CHAR *)display_STRING_1_English, sizeof(display_STRING_1_English) - 1}
};

/*  Language Table                                                             */


GX_CONST GX_STRING *display_language_table[1] = 
{
    display_English_string_table,
};

GX_THEME display_theme_1 =
{
    (GX_COLOR *) display_theme_1_color_table,
    (GX_FONT **) display_theme_1_font_table,
    (GX_PIXELMAP **) display_theme_1_pixelmap_table,
    NULL,
    {
        20,                                  /* scroll width                   */
        18,                                  /* thumb width                    */
        20,                                  /* thumb travel min               */
        20,                                  /* thumb travel max               */
        4,                                   /* thumb border style             */
        0,                                   /* scroll fill pixelmap           */
        0,                                   /* scroll thumb pixelmap          */
        0,                                   /* scroll up pixelmap             */
        0,                                   /* scroll down pixelmap           */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb color             */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb border color      */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll button color            */
    },
    {
        20,                                  /* scroll width                   */
        18,                                  /* thumb width                    */
        20,                                  /* thumb travel min               */
        20,                                  /* thumb travel max               */
        4,                                   /* thumb border style             */
        0,                                   /* scroll fill pixelmap           */
        0,                                   /* scroll thumb pixelmap          */
        0,                                   /* scroll up pixelmap             */
        0,                                   /* scroll down pixelmap           */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll thumb color             */
        GX_COLOR_ID_CANVAS,                  /* scroll thumb border color      */
        GX_COLOR_ID_SCROLL_BUTTON,           /* scroll button color            */
    },
    GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_END_BUTTONS|GX_SCROLLBAR_VERTICAL,
    GX_SCROLLBAR_RELATIVE_THUMB|GX_SCROLLBAR_END_BUTTONS|GX_SCROLLBAR_HORIZONTAL,
    29,                                      /* color table size               */
    5,                                       /* font table size                */
    5,                                       /* pixelmap table size            */
    0                                        /* palette size                   */

};
GX_CONST GX_THEME *display_theme_table[1] =
{
    &display_theme_1
};

