/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.0.0                                               */
/*  Date (dd.mm.yyyy): 18.11.2020   Time (hh:mm): 16:54                        */
/*******************************************************************************/


#ifndef _FLIPDOT_GUIX_DISPLAY_RESOURCES_H_
#define _FLIPDOT_GUIX_DISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY 0
#define DISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_MONOCHROME
#define DISPLAY_X_RESOLUTION 28
#define DISPLAY_Y_RESOLUTION 14
#define DISPLAY_THEME_1 0
#define DISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define DISPLAY_COLOR_TABLE_SIZE 29

/* Font ID definitions                                                         */

#define GX_FONT_ID_FLIPDOTFONT3BY5 4
#define DISPLAY_FONT_TABLE_SIZE 5

/* Pixelmap ID definitions                                                     */

#define DISPLAY_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define GX_STRING_ID_STRING_4 4
#define GX_STRING_ID_STRING_5 5
#define GX_STRING_ID_STRING_6 6
#define GX_STRING_ID_STRING_7 7
#define GX_STRING_ID_STRING_8 8
#define GX_STRING_ID_STRING_9 9
#define GX_STRING_ID_STRING_10 10
#define GX_STRING_ID_STRING_11 11
#define DISPLAY_STRING_TABLE_SIZE 12

#endif                                       /* sentry                         */
